// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decrypt_it`, `encrypt_it`, `generate_submaster_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EncryptedRecordFile`

Future<Uint8List> encryptPayload({
  required List<int> payload,
  required U8Array32 masterKey,
}) => RustLib.instance.api.crateApiCryptoEncryptPayload(
  payload: payload,
  masterKey: masterKey,
);

Future<Uint8List> decryptPayload({
  required List<int> encryptedJsonBytes,
  required U8Array32 masterKey,
}) => RustLib.instance.api.crateApiCryptoDecryptPayload(
  encryptedJsonBytes: encryptedJsonBytes,
  masterKey: masterKey,
);

Future<U8Array64> deriveMasterKey({
  required String password,
  required List<int> salt,
}) => RustLib.instance.api.crateApiCryptoDeriveMasterKey(
  password: password,
  salt: salt,
);

Future<(U8Array32, U8Array32)> splitMasterKey({required U8Array64 masterKey}) =>
    RustLib.instance.api.crateApiCryptoSplitMasterKey(masterKey: masterKey);

Future<U8Array16> generateSalt() =>
    RustLib.instance.api.crateApiCryptoGenerateSalt();

class U8Array16 extends NonGrowableListView<int> {
  static const arraySize = 16;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array16(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array16.init() : this(Uint8List(arraySize));
}

class U8Array32 extends NonGrowableListView<int> {
  static const arraySize = 32;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array32(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array32.init() : this(Uint8List(arraySize));
}

class U8Array64 extends NonGrowableListView<int> {
  static const arraySize = 64;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array64(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array64.init() : this(Uint8List(arraySize));
}
