// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'vault_models.dart';

// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `add_entry`

VaultMetadataVault createEmptyVault() =>
    RustLib.instance.api.crateApiVaultMetadataCreateEmptyVault();

VaultMetadataVault addEntryToVault({
  required VaultMetadataVault vault,
  required String name,
  required EntryCategory category,
  String? folder,
  String? icon,
}) => RustLib.instance.api.crateApiVaultMetadataAddEntryToVault(
  vault: vault,
  name: name,
  category: category,
  folder: folder,
  icon: icon,
);
