// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'vault_models.dart';

// These functions are ignored because they are not marked as `pub`: `update_vault`

VaultManager createVaultManager({
  required String rootPath,
  required String password,
}) => RustLib.instance.api.crateApiVaultManagerCreateVaultManager(
  rootPath: rootPath,
  password: password,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VaultManager>>
abstract class VaultManager implements RustOpaqueInterface {
  void addEntry({
    required String name,
    required EntryCategory category,
    String? folder,
    String? icon,
  });

  void addFolder({required String name});

  static Future<VaultManager> default_() =>
      RustLib.instance.api.crateApiVaultManagerVaultManagerDefault();

  VaultMetadataVault getMetadata();

  void removeFolder({required String id});
}
