// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'api/generator.dart';
import 'api/vault_manager.dart';
import 'api/vault_models.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiMainInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.10.0';

  @override
  int get rustContentHash => -1466180147;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'pass_tool_core',
        ioDirectory: '../../vaultcore/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiVaultManagerVaultManagerAddEntry({
    required VaultManager that,
    required String name,
    required EntryCategory category,
    String? folder,
    String? icon,
  });

  void crateApiVaultManagerVaultManagerAddFolder({
    required VaultManager that,
    required String name,
  });

  Future<VaultManager> crateApiVaultManagerVaultManagerDefault();

  VaultMetadataVault crateApiVaultManagerVaultManagerGetMetadata({
    required VaultManager that,
  });

  void crateApiVaultManagerVaultManagerRemoveFolder({
    required VaultManager that,
    required String id,
  });

  Future<void> crateApiVaultModelsVaultMetadataVaultAddEntry({
    required VaultMetadataVault that,
    required String name,
    required EntryCategory category,
    String? folder,
    String? icon,
  });

  Future<Folder> crateApiVaultModelsVaultMetadataVaultAddFolder({
    required VaultMetadataVault that,
    required String name,
  });

  Map<EntryCategory, BigInt>
  crateApiVaultModelsVaultMetadataVaultAutoAccessorGetCategoryCounts({
    required VaultMetadataVault that,
  });

  List<VaultMetadataEntry>
  crateApiVaultModelsVaultMetadataVaultAutoAccessorGetEntries({
    required VaultMetadataVault that,
  });

  Map<String, BigInt>
  crateApiVaultModelsVaultMetadataVaultAutoAccessorGetFolderCounts({
    required VaultMetadataVault that,
  });

  List<Folder> crateApiVaultModelsVaultMetadataVaultAutoAccessorGetFolders({
    required VaultMetadataVault that,
  });

  BigInt crateApiVaultModelsVaultMetadataVaultAutoAccessorGetTrashedCount({
    required VaultMetadataVault that,
  });

  void crateApiVaultModelsVaultMetadataVaultAutoAccessorSetCategoryCounts({
    required VaultMetadataVault that,
    required Map<EntryCategory, BigInt> categoryCounts,
  });

  void crateApiVaultModelsVaultMetadataVaultAutoAccessorSetEntries({
    required VaultMetadataVault that,
    required List<VaultMetadataEntry> entries,
  });

  void crateApiVaultModelsVaultMetadataVaultAutoAccessorSetFolderCounts({
    required VaultMetadataVault that,
    required Map<String, BigInt> folderCounts,
  });

  void crateApiVaultModelsVaultMetadataVaultAutoAccessorSetFolders({
    required VaultMetadataVault that,
    required List<Folder> folders,
  });

  void crateApiVaultModelsVaultMetadataVaultAutoAccessorSetTrashedCount({
    required VaultMetadataVault that,
    required BigInt trashedCount,
  });

  Future<VaultMetadataVault> crateApiVaultModelsVaultMetadataVaultDefault();

  Future<void> crateApiVaultModelsVaultMetadataVaultRecalculateCounts({
    required VaultMetadataVault that,
  });

  Future<bool> crateApiVaultModelsVaultMetadataVaultRemoveFolderById({
    required VaultMetadataVault that,
    required String folderId,
  });

  VaultManager crateApiVaultManagerCreateVaultManager({
    required String rootPath,
    required String password,
  });

  Future<Uint8List> crateApiCryptoDecryptPayload({
    required List<int> encryptedJsonBytes,
    required U8Array32 masterKey,
  });

  Future<U8Array64> crateApiCryptoDeriveMasterKey({
    required String password,
    required List<int> salt,
  });

  Future<Uint8List> crateApiCryptoEncryptPayload({
    required List<int> payload,
    required U8Array32 masterKey,
  });

  String crateApiGeneratorGeneratePassword({
    required BigInt length,
    required bool includeLower,
    required bool includeUpper,
    required bool includeDigits,
    required bool includeSymbols,
    required BigInt minDigits,
    required BigInt minSymbols,
  });

  Future<U8Array16> crateApiCryptoGenerateSalt();

  Future<void> crateApiMainInitApp();

  Future<(U8Array32, U8Array32)> crateApiCryptoSplitMasterKey({
    required U8Array64 masterKey,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_VaultManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_VaultManager;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_VaultManagerPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_VaultMetadataVault;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_VaultMetadataVault;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VaultMetadataVaultPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiVaultManagerVaultManagerAddEntry({
    required VaultManager that,
    required String name,
    required EntryCategory category,
    String? folder,
    String? icon,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          sse_encode_entry_category(category, serializer);
          sse_encode_opt_String(folder, serializer);
          sse_encode_opt_String(icon, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultManagerVaultManagerAddEntryConstMeta,
        argValues: [that, name, category, folder, icon],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultManagerVaultManagerAddEntryConstMeta =>
      const TaskConstMeta(
        debugName: "VaultManager_add_entry",
        argNames: ["that", "name", "category", "folder", "icon"],
      );

  @override
  void crateApiVaultManagerVaultManagerAddFolder({
    required VaultManager that,
    required String name,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultManagerVaultManagerAddFolderConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultManagerVaultManagerAddFolderConstMeta =>
      const TaskConstMeta(
        debugName: "VaultManager_add_folder",
        argNames: ["that", "name"],
      );

  @override
  Future<VaultManager> crateApiVaultManagerVaultManagerDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultManagerVaultManagerDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultManagerVaultManagerDefaultConstMeta =>
      const TaskConstMeta(debugName: "VaultManager_default", argNames: []);

  @override
  VaultMetadataVault crateApiVaultManagerVaultManagerGetMetadata({
    required VaultManager that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultManagerVaultManagerGetMetadataConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultManagerVaultManagerGetMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "VaultManager_get_metadata",
        argNames: ["that"],
      );

  @override
  void crateApiVaultManagerVaultManagerRemoveFolder({
    required VaultManager that,
    required String id,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultManagerVaultManagerRemoveFolderConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultManagerVaultManagerRemoveFolderConstMeta =>
      const TaskConstMeta(
        debugName: "VaultManager_remove_folder",
        argNames: ["that", "id"],
      );

  @override
  Future<void> crateApiVaultModelsVaultMetadataVaultAddEntry({
    required VaultMetadataVault that,
    required String name,
    required EntryCategory category,
    String? folder,
    String? icon,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          sse_encode_entry_category(category, serializer);
          sse_encode_opt_String(folder, serializer);
          sse_encode_opt_String(icon, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultModelsVaultMetadataVaultAddEntryConstMeta,
        argValues: [that, name, category, folder, icon],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultModelsVaultMetadataVaultAddEntryConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_add_entry",
        argNames: ["that", "name", "category", "folder", "icon"],
      );

  @override
  Future<Folder> crateApiVaultModelsVaultMetadataVaultAddFolder({
    required VaultMetadataVault that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_folder,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultModelsVaultMetadataVaultAddFolderConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultModelsVaultMetadataVaultAddFolderConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_add_folder",
        argNames: ["that", "name"],
      );

  @override
  Map<EntryCategory, BigInt>
  crateApiVaultModelsVaultMetadataVaultAutoAccessorGetCategoryCounts({
    required VaultMetadataVault that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Map_entry_category_usize_None,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiVaultModelsVaultMetadataVaultAutoAccessorGetCategoryCountsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiVaultModelsVaultMetadataVaultAutoAccessorGetCategoryCountsConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_auto_accessor_get_category_counts",
        argNames: ["that"],
      );

  @override
  List<VaultMetadataEntry>
  crateApiVaultModelsVaultMetadataVaultAutoAccessorGetEntries({
    required VaultMetadataVault that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_vault_metadata_entry,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiVaultModelsVaultMetadataVaultAutoAccessorGetEntriesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiVaultModelsVaultMetadataVaultAutoAccessorGetEntriesConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_auto_accessor_get_entries",
        argNames: ["that"],
      );

  @override
  Map<String, BigInt>
  crateApiVaultModelsVaultMetadataVaultAutoAccessorGetFolderCounts({
    required VaultMetadataVault that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Map_String_usize_None,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiVaultModelsVaultMetadataVaultAutoAccessorGetFolderCountsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiVaultModelsVaultMetadataVaultAutoAccessorGetFolderCountsConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_auto_accessor_get_folder_counts",
        argNames: ["that"],
      );

  @override
  List<Folder> crateApiVaultModelsVaultMetadataVaultAutoAccessorGetFolders({
    required VaultMetadataVault that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_folder,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiVaultModelsVaultMetadataVaultAutoAccessorGetFoldersConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiVaultModelsVaultMetadataVaultAutoAccessorGetFoldersConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_auto_accessor_get_folders",
        argNames: ["that"],
      );

  @override
  BigInt crateApiVaultModelsVaultMetadataVaultAutoAccessorGetTrashedCount({
    required VaultMetadataVault that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiVaultModelsVaultMetadataVaultAutoAccessorGetTrashedCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiVaultModelsVaultMetadataVaultAutoAccessorGetTrashedCountConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_auto_accessor_get_trashed_count",
        argNames: ["that"],
      );

  @override
  void crateApiVaultModelsVaultMetadataVaultAutoAccessorSetCategoryCounts({
    required VaultMetadataVault that,
    required Map<EntryCategory, BigInt> categoryCounts,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          sse_encode_Map_entry_category_usize_None(categoryCounts, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiVaultModelsVaultMetadataVaultAutoAccessorSetCategoryCountsConstMeta,
        argValues: [that, categoryCounts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiVaultModelsVaultMetadataVaultAutoAccessorSetCategoryCountsConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_auto_accessor_set_category_counts",
        argNames: ["that", "categoryCounts"],
      );

  @override
  void crateApiVaultModelsVaultMetadataVaultAutoAccessorSetEntries({
    required VaultMetadataVault that,
    required List<VaultMetadataEntry> entries,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          sse_encode_list_vault_metadata_entry(entries, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiVaultModelsVaultMetadataVaultAutoAccessorSetEntriesConstMeta,
        argValues: [that, entries],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiVaultModelsVaultMetadataVaultAutoAccessorSetEntriesConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_auto_accessor_set_entries",
        argNames: ["that", "entries"],
      );

  @override
  void crateApiVaultModelsVaultMetadataVaultAutoAccessorSetFolderCounts({
    required VaultMetadataVault that,
    required Map<String, BigInt> folderCounts,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          sse_encode_Map_String_usize_None(folderCounts, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiVaultModelsVaultMetadataVaultAutoAccessorSetFolderCountsConstMeta,
        argValues: [that, folderCounts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiVaultModelsVaultMetadataVaultAutoAccessorSetFolderCountsConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_auto_accessor_set_folder_counts",
        argNames: ["that", "folderCounts"],
      );

  @override
  void crateApiVaultModelsVaultMetadataVaultAutoAccessorSetFolders({
    required VaultMetadataVault that,
    required List<Folder> folders,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          sse_encode_list_folder(folders, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiVaultModelsVaultMetadataVaultAutoAccessorSetFoldersConstMeta,
        argValues: [that, folders],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiVaultModelsVaultMetadataVaultAutoAccessorSetFoldersConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_auto_accessor_set_folders",
        argNames: ["that", "folders"],
      );

  @override
  void crateApiVaultModelsVaultMetadataVaultAutoAccessorSetTrashedCount({
    required VaultMetadataVault that,
    required BigInt trashedCount,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          sse_encode_usize(trashedCount, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiVaultModelsVaultMetadataVaultAutoAccessorSetTrashedCountConstMeta,
        argValues: [that, trashedCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiVaultModelsVaultMetadataVaultAutoAccessorSetTrashedCountConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_auto_accessor_set_trashed_count",
        argNames: ["that", "trashedCount"],
      );

  @override
  Future<VaultMetadataVault> crateApiVaultModelsVaultMetadataVaultDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultModelsVaultMetadataVaultDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultModelsVaultMetadataVaultDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_default",
        argNames: [],
      );

  @override
  Future<void> crateApiVaultModelsVaultMetadataVaultRecalculateCounts({
    required VaultMetadataVault that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiVaultModelsVaultMetadataVaultRecalculateCountsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiVaultModelsVaultMetadataVaultRecalculateCountsConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_recalculate_counts",
        argNames: ["that"],
      );

  @override
  Future<bool> crateApiVaultModelsVaultMetadataVaultRemoveFolderById({
    required VaultMetadataVault that,
    required String folderId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
            that,
            serializer,
          );
          sse_encode_String(folderId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiVaultModelsVaultMetadataVaultRemoveFolderByIdConstMeta,
        argValues: [that, folderId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiVaultModelsVaultMetadataVaultRemoveFolderByIdConstMeta =>
      const TaskConstMeta(
        debugName: "VaultMetadataVault_remove_folder_by_id",
        argNames: ["that", "folderId"],
      );

  @override
  VaultManager crateApiVaultManagerCreateVaultManager({
    required String rootPath,
    required String password,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootPath, serializer);
          sse_encode_String(password, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultManagerCreateVaultManagerConstMeta,
        argValues: [rootPath, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultManagerCreateVaultManagerConstMeta =>
      const TaskConstMeta(
        debugName: "create_vault_manager",
        argNames: ["rootPath", "password"],
      );

  @override
  Future<Uint8List> crateApiCryptoDecryptPayload({
    required List<int> encryptedJsonBytes,
    required U8Array32 masterKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(encryptedJsonBytes, serializer);
          sse_encode_u_8_array_32(masterKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoDecryptPayloadConstMeta,
        argValues: [encryptedJsonBytes, masterKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoDecryptPayloadConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_payload",
        argNames: ["encryptedJsonBytes", "masterKey"],
      );

  @override
  Future<U8Array64> crateApiCryptoDeriveMasterKey({
    required String password,
    required List<int> salt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          sse_encode_list_prim_u_8_loose(salt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoDeriveMasterKeyConstMeta,
        argValues: [password, salt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoDeriveMasterKeyConstMeta =>
      const TaskConstMeta(
        debugName: "derive_master_key",
        argNames: ["password", "salt"],
      );

  @override
  Future<Uint8List> crateApiCryptoEncryptPayload({
    required List<int> payload,
    required U8Array32 masterKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(payload, serializer);
          sse_encode_u_8_array_32(masterKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoEncryptPayloadConstMeta,
        argValues: [payload, masterKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoEncryptPayloadConstMeta =>
      const TaskConstMeta(
        debugName: "encrypt_payload",
        argNames: ["payload", "masterKey"],
      );

  @override
  String crateApiGeneratorGeneratePassword({
    required BigInt length,
    required bool includeLower,
    required bool includeUpper,
    required bool includeDigits,
    required bool includeSymbols,
    required BigInt minDigits,
    required BigInt minSymbols,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(length, serializer);
          sse_encode_bool(includeLower, serializer);
          sse_encode_bool(includeUpper, serializer);
          sse_encode_bool(includeDigits, serializer);
          sse_encode_bool(includeSymbols, serializer);
          sse_encode_usize(minDigits, serializer);
          sse_encode_usize(minSymbols, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGeneratorGeneratePasswordConstMeta,
        argValues: [
          length,
          includeLower,
          includeUpper,
          includeDigits,
          includeSymbols,
          minDigits,
          minSymbols,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGeneratorGeneratePasswordConstMeta =>
      const TaskConstMeta(
        debugName: "generate_password",
        argNames: [
          "length",
          "includeLower",
          "includeUpper",
          "includeDigits",
          "includeSymbols",
          "minDigits",
          "minSymbols",
        ],
      );

  @override
  Future<U8Array16> crateApiCryptoGenerateSalt() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoGenerateSaltConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoGenerateSaltConstMeta =>
      const TaskConstMeta(debugName: "generate_salt", argNames: []);

  @override
  Future<void> crateApiMainInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMainInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMainInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<(U8Array32, U8Array32)> crateApiCryptoSplitMasterKey({
    required U8Array64 masterKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8_array_64(masterKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_u_8_array_32_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoSplitMasterKeyConstMeta,
        argValues: [masterKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoSplitMasterKeyConstMeta =>
      const TaskConstMeta(
        debugName: "split_master_key",
        argNames: ["masterKey"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_VaultManager => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_VaultManager => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_VaultMetadataVault => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_VaultMetadataVault => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault;

  @protected
  VaultManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VaultMetadataVault
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultMetadataVaultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VaultManager
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VaultMetadataVault
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultMetadataVaultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VaultManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VaultMetadataVault
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultMetadataVaultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Map<String, BigInt> dco_decode_Map_String_usize_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_usize(raw).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  Map<EntryCategory, BigInt> dco_decode_Map_entry_category_usize_None(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_entry_category_usize(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  VaultManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VaultMetadataVault
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultMetadataVaultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EntryCategory dco_decode_entry_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EntryCategory.values[raw as int];
  }

  @protected
  Folder dco_decode_folder(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Folder(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<Folder> dco_decode_list_folder(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_folder).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(EntryCategory, BigInt)> dco_decode_list_record_entry_category_usize(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_entry_category_usize)
        .toList();
  }

  @protected
  List<(String, BigInt)> dco_decode_list_record_string_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_usize).toList();
  }

  @protected
  List<VaultMetadataEntry> dco_decode_list_vault_metadata_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_vault_metadata_entry).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  (EntryCategory, BigInt) dco_decode_record_entry_category_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_entry_category(arr[0]), dco_decode_usize(arr[1]));
  }

  @protected
  (String, BigInt) dco_decode_record_string_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_usize(arr[1]));
  }

  @protected
  (U8Array32, U8Array32) dco_decode_record_u_8_array_32_u_8_array_32(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_u_8_array_32(arr[0]), dco_decode_u_8_array_32(arr[1]));
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  U8Array16 dco_decode_u_8_array_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array16(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  U8Array32 dco_decode_u_8_array_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array32(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  U8Array64 dco_decode_u_8_array_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array64(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VaultMetadataEntry dco_decode_vault_metadata_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return VaultMetadataEntry(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      category: dco_decode_entry_category(arr[2]),
      folder: dco_decode_opt_String(arr[3]),
      updatedAt: dco_decode_i_64(arr[4]),
      version: dco_decode_u_32(arr[5]),
      isTrashed: dco_decode_bool(arr[6]),
      icon: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  VaultManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VaultMetadataVault
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultMetadataVaultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VaultManager
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VaultMetadataVault
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultMetadataVaultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VaultManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VaultMetadataVault
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultMetadataVaultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Map<String, BigInt> sse_decode_Map_String_usize_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_usize(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  Map<EntryCategory, BigInt> sse_decode_Map_entry_category_usize_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_entry_category_usize(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  VaultManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VaultMetadataVault
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultMetadataVaultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EntryCategory sse_decode_entry_category(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return EntryCategory.values[inner];
  }

  @protected
  Folder sse_decode_folder(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return Folder(id: var_id, name: var_name);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<Folder> sse_decode_list_folder(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Folder>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_folder(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(EntryCategory, BigInt)> sse_decode_list_record_entry_category_usize(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(EntryCategory, BigInt)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_entry_category_usize(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, BigInt)> sse_decode_list_record_string_usize(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, BigInt)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_usize(deserializer));
    }
    return ans_;
  }

  @protected
  List<VaultMetadataEntry> sse_decode_list_vault_metadata_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VaultMetadataEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_vault_metadata_entry(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (EntryCategory, BigInt) sse_decode_record_entry_category_usize(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_entry_category(deserializer);
    var var_field1 = sse_decode_usize(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, BigInt) sse_decode_record_string_usize(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_usize(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (U8Array32, U8Array32) sse_decode_record_u_8_array_32_u_8_array_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_u_8_array_32(deserializer);
    var var_field1 = sse_decode_u_8_array_32(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  U8Array16 sse_decode_u_8_array_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array16(inner);
  }

  @protected
  U8Array32 sse_decode_u_8_array_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array32(inner);
  }

  @protected
  U8Array64 sse_decode_u_8_array_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array64(inner);
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VaultMetadataEntry sse_decode_vault_metadata_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_category = sse_decode_entry_category(deserializer);
    var var_folder = sse_decode_opt_String(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    var var_version = sse_decode_u_32(deserializer);
    var var_isTrashed = sse_decode_bool(deserializer);
    var var_icon = sse_decode_opt_String(deserializer);
    return VaultMetadataEntry(
      id: var_id,
      name: var_name,
      category: var_category,
      folder: var_folder,
      updatedAt: var_updatedAt,
      version: var_version,
      isTrashed: var_isTrashed,
      icon: var_icon,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    VaultManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultManagerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    VaultMetadataVault self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultMetadataVaultImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    VaultManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultManagerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    VaultMetadataVault self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultMetadataVaultImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    VaultManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultManagerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    VaultMetadataVault self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultMetadataVaultImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_usize_None(
    Map<String, BigInt> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_usize(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_entry_category_usize_None(
    Map<EntryCategory, BigInt> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_entry_category_usize(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    VaultManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultManagerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    VaultMetadataVault self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultMetadataVaultImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_entry_category(EntryCategory self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_folder(Folder self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_folder(List<Folder> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_folder(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_entry_category_usize(
    List<(EntryCategory, BigInt)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_entry_category_usize(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_usize(
    List<(String, BigInt)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_usize(item, serializer);
    }
  }

  @protected
  void sse_encode_list_vault_metadata_entry(
    List<VaultMetadataEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_vault_metadata_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_record_entry_category_usize(
    (EntryCategory, BigInt) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_entry_category(self.$1, serializer);
    sse_encode_usize(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_usize(
    (String, BigInt) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_usize(self.$2, serializer);
  }

  @protected
  void sse_encode_record_u_8_array_32_u_8_array_32(
    (U8Array32, U8Array32) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8_array_32(self.$1, serializer);
    sse_encode_u_8_array_32(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_u_8_array_16(U8Array16 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_u_8_array_32(U8Array32 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_u_8_array_64(U8Array64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vault_metadata_entry(
    VaultMetadataEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_entry_category(self.category, serializer);
    sse_encode_opt_String(self.folder, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
    sse_encode_u_32(self.version, serializer);
    sse_encode_bool(self.isTrashed, serializer);
    sse_encode_opt_String(self.icon, serializer);
  }
}

@sealed
class VaultManagerImpl extends RustOpaque implements VaultManager {
  // Not to be used by end users
  VaultManagerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  VaultManagerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_VaultManager,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_VaultManager,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_VaultManagerPtr,
  );

  void addEntry({
    required String name,
    required EntryCategory category,
    String? folder,
    String? icon,
  }) => RustLib.instance.api.crateApiVaultManagerVaultManagerAddEntry(
    that: this,
    name: name,
    category: category,
    folder: folder,
    icon: icon,
  );

  void addFolder({required String name}) => RustLib.instance.api
      .crateApiVaultManagerVaultManagerAddFolder(that: this, name: name);

  VaultMetadataVault getMetadata() => RustLib.instance.api
      .crateApiVaultManagerVaultManagerGetMetadata(that: this);

  void removeFolder({required String id}) => RustLib.instance.api
      .crateApiVaultManagerVaultManagerRemoveFolder(that: this, id: id);
}

@sealed
class VaultMetadataVaultImpl extends RustOpaque implements VaultMetadataVault {
  // Not to be used by end users
  VaultMetadataVaultImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  VaultMetadataVaultImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_VaultMetadataVault,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_VaultMetadataVault,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_VaultMetadataVaultPtr,
  );

  Future<void> addEntry({
    required String name,
    required EntryCategory category,
    String? folder,
    String? icon,
  }) => RustLib.instance.api.crateApiVaultModelsVaultMetadataVaultAddEntry(
    that: this,
    name: name,
    category: category,
    folder: folder,
    icon: icon,
  );

  Future<Folder> addFolder({required String name}) => RustLib.instance.api
      .crateApiVaultModelsVaultMetadataVaultAddFolder(that: this, name: name);

  Map<EntryCategory, BigInt> get categoryCounts => RustLib.instance.api
      .crateApiVaultModelsVaultMetadataVaultAutoAccessorGetCategoryCounts(
        that: this,
      );

  List<VaultMetadataEntry> get entries => RustLib.instance.api
      .crateApiVaultModelsVaultMetadataVaultAutoAccessorGetEntries(that: this);

  Map<String, BigInt> get folderCounts => RustLib.instance.api
      .crateApiVaultModelsVaultMetadataVaultAutoAccessorGetFolderCounts(
        that: this,
      );

  List<Folder> get folders => RustLib.instance.api
      .crateApiVaultModelsVaultMetadataVaultAutoAccessorGetFolders(that: this);

  BigInt get trashedCount => RustLib.instance.api
      .crateApiVaultModelsVaultMetadataVaultAutoAccessorGetTrashedCount(
        that: this,
      );

  set categoryCounts(Map<EntryCategory, BigInt> categoryCounts) => RustLib
      .instance
      .api
      .crateApiVaultModelsVaultMetadataVaultAutoAccessorSetCategoryCounts(
        that: this,
        categoryCounts: categoryCounts,
      );

  set entries(List<VaultMetadataEntry> entries) => RustLib.instance.api
      .crateApiVaultModelsVaultMetadataVaultAutoAccessorSetEntries(
        that: this,
        entries: entries,
      );

  set folderCounts(Map<String, BigInt> folderCounts) => RustLib.instance.api
      .crateApiVaultModelsVaultMetadataVaultAutoAccessorSetFolderCounts(
        that: this,
        folderCounts: folderCounts,
      );

  set folders(List<Folder> folders) => RustLib.instance.api
      .crateApiVaultModelsVaultMetadataVaultAutoAccessorSetFolders(
        that: this,
        folders: folders,
      );

  set trashedCount(BigInt trashedCount) => RustLib.instance.api
      .crateApiVaultModelsVaultMetadataVaultAutoAccessorSetTrashedCount(
        that: this,
        trashedCount: trashedCount,
      );

  Future<void> recalculateCounts() => RustLib.instance.api
      .crateApiVaultModelsVaultMetadataVaultRecalculateCounts(that: this);

  Future<bool> removeFolderById({required String folderId}) => RustLib
      .instance
      .api
      .crateApiVaultModelsVaultMetadataVaultRemoveFolderById(
        that: this,
        folderId: folderId,
      );
}
