// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'api/generator.dart';
import 'api/vault_manager.dart';
import 'api/vault_models.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CryptoErrorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoErrorPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VaultManagerPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VaultManagerErrorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerErrorPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VaultMetadataVaultPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVaultPtr;

  @protected
  CryptoError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    dynamic raw,
  );

  @protected
  VaultManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    dynamic raw,
  );

  @protected
  VaultManagerError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError(
    dynamic raw,
  );

  @protected
  VaultMetadataVault
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    dynamic raw,
  );

  @protected
  VaultManager
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    dynamic raw,
  );

  @protected
  VaultMetadataVault
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    dynamic raw,
  );

  @protected
  VaultManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    dynamic raw,
  );

  @protected
  VaultMetadataVault
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    dynamic raw,
  );

  @protected
  Map<String, BigInt> dco_decode_Map_String_usize_None(dynamic raw);

  @protected
  Map<EntryCategory, BigInt> dco_decode_Map_entry_category_usize_None(
    dynamic raw,
  );

  @protected
  CryptoError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    dynamic raw,
  );

  @protected
  VaultManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    dynamic raw,
  );

  @protected
  VaultManagerError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError(
    dynamic raw,
  );

  @protected
  VaultMetadataVault
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  VaultPayload dco_decode_TraitDef_VaultPayload(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CreditCardRecord dco_decode_box_autoadd_credit_card_record(dynamic raw);

  @protected
  LoginRecord dco_decode_box_autoadd_login_record(dynamic raw);

  @protected
  SecureNoteRecord dco_decode_box_autoadd_secure_note_record(dynamic raw);

  @protected
  TOTPConfig dco_decode_box_autoadd_totp_config(dynamic raw);

  @protected
  CreditCardRecord dco_decode_credit_card_record(dynamic raw);

  @protected
  EntryCategory dco_decode_entry_category(dynamic raw);

  @protected
  Folder dco_decode_folder(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Folder> dco_decode_list_folder(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(EntryCategory, BigInt)> dco_decode_list_record_entry_category_usize(
    dynamic raw,
  );

  @protected
  List<(String, BigInt)> dco_decode_list_record_string_usize(dynamic raw);

  @protected
  List<SiteMapping> dco_decode_list_site_mapping(dynamic raw);

  @protected
  List<VaultMetadataEntry> dco_decode_list_vault_metadata_entry(dynamic raw);

  @protected
  LoginRecord dco_decode_login_record(dynamic raw);

  @protected
  MatchType dco_decode_match_type(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  TOTPConfig? dco_decode_opt_box_autoadd_totp_config(dynamic raw);

  @protected
  (EntryCategory, BigInt) dco_decode_record_entry_category_usize(dynamic raw);

  @protected
  (String, BigInt) dco_decode_record_string_usize(dynamic raw);

  @protected
  (U8Array32, U8Array32) dco_decode_record_u_8_array_32_u_8_array_32(
    dynamic raw,
  );

  @protected
  SecureNoteRecord dco_decode_secure_note_record(dynamic raw);

  @protected
  SiteMapping dco_decode_site_mapping(dynamic raw);

  @protected
  TOTPAlgorithm dco_decode_totp_algorithm(dynamic raw);

  @protected
  TOTPConfig dco_decode_totp_config(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  U8Array16 dco_decode_u_8_array_16(dynamic raw);

  @protected
  U8Array32 dco_decode_u_8_array_32(dynamic raw);

  @protected
  U8Array64 dco_decode_u_8_array_64(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VaultMetadataEntry dco_decode_vault_metadata_entry(dynamic raw);

  @protected
  CryptoError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    SseDeserializer deserializer,
  );

  @protected
  VaultManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    SseDeserializer deserializer,
  );

  @protected
  VaultManagerError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError(
    SseDeserializer deserializer,
  );

  @protected
  VaultMetadataVault
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    SseDeserializer deserializer,
  );

  @protected
  VaultManager
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    SseDeserializer deserializer,
  );

  @protected
  VaultMetadataVault
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    SseDeserializer deserializer,
  );

  @protected
  VaultManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    SseDeserializer deserializer,
  );

  @protected
  VaultMetadataVault
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, BigInt> sse_decode_Map_String_usize_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<EntryCategory, BigInt> sse_decode_Map_entry_category_usize_None(
    SseDeserializer deserializer,
  );

  @protected
  CryptoError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    SseDeserializer deserializer,
  );

  @protected
  VaultManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    SseDeserializer deserializer,
  );

  @protected
  VaultManagerError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError(
    SseDeserializer deserializer,
  );

  @protected
  VaultMetadataVault
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CreditCardRecord sse_decode_box_autoadd_credit_card_record(
    SseDeserializer deserializer,
  );

  @protected
  LoginRecord sse_decode_box_autoadd_login_record(SseDeserializer deserializer);

  @protected
  SecureNoteRecord sse_decode_box_autoadd_secure_note_record(
    SseDeserializer deserializer,
  );

  @protected
  TOTPConfig sse_decode_box_autoadd_totp_config(SseDeserializer deserializer);

  @protected
  CreditCardRecord sse_decode_credit_card_record(SseDeserializer deserializer);

  @protected
  EntryCategory sse_decode_entry_category(SseDeserializer deserializer);

  @protected
  Folder sse_decode_folder(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Folder> sse_decode_list_folder(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(EntryCategory, BigInt)> sse_decode_list_record_entry_category_usize(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, BigInt)> sse_decode_list_record_string_usize(
    SseDeserializer deserializer,
  );

  @protected
  List<SiteMapping> sse_decode_list_site_mapping(SseDeserializer deserializer);

  @protected
  List<VaultMetadataEntry> sse_decode_list_vault_metadata_entry(
    SseDeserializer deserializer,
  );

  @protected
  LoginRecord sse_decode_login_record(SseDeserializer deserializer);

  @protected
  MatchType sse_decode_match_type(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  TOTPConfig? sse_decode_opt_box_autoadd_totp_config(
    SseDeserializer deserializer,
  );

  @protected
  (EntryCategory, BigInt) sse_decode_record_entry_category_usize(
    SseDeserializer deserializer,
  );

  @protected
  (String, BigInt) sse_decode_record_string_usize(SseDeserializer deserializer);

  @protected
  (U8Array32, U8Array32) sse_decode_record_u_8_array_32_u_8_array_32(
    SseDeserializer deserializer,
  );

  @protected
  SecureNoteRecord sse_decode_secure_note_record(SseDeserializer deserializer);

  @protected
  SiteMapping sse_decode_site_mapping(SseDeserializer deserializer);

  @protected
  TOTPAlgorithm sse_decode_totp_algorithm(SseDeserializer deserializer);

  @protected
  TOTPConfig sse_decode_totp_config(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  U8Array16 sse_decode_u_8_array_16(SseDeserializer deserializer);

  @protected
  U8Array32 sse_decode_u_8_array_32(SseDeserializer deserializer);

  @protected
  U8Array64 sse_decode_u_8_array_64(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VaultMetadataEntry sse_decode_vault_metadata_entry(
    SseDeserializer deserializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    CryptoError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    VaultManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError(
    VaultManagerError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    VaultMetadataVault self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    VaultManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    VaultMetadataVault self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    VaultManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    VaultMetadataVault self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_usize_None(
    Map<String, BigInt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_entry_category_usize_None(
    Map<EntryCategory, BigInt> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    CryptoError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    VaultManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError(
    VaultManagerError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    VaultMetadataVault self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_credit_card_record(
    CreditCardRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_login_record(
    LoginRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_secure_note_record(
    SecureNoteRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_totp_config(
    TOTPConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_credit_card_record(
    CreditCardRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entry_category(EntryCategory self, SseSerializer serializer);

  @protected
  void sse_encode_folder(Folder self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_folder(List<Folder> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_entry_category_usize(
    List<(EntryCategory, BigInt)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_usize(
    List<(String, BigInt)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_site_mapping(
    List<SiteMapping> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vault_metadata_entry(
    List<VaultMetadataEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_login_record(LoginRecord self, SseSerializer serializer);

  @protected
  void sse_encode_match_type(MatchType self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_totp_config(
    TOTPConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_entry_category_usize(
    (EntryCategory, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_usize(
    (String, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_8_array_32_u_8_array_32(
    (U8Array32, U8Array32) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_secure_note_record(
    SecureNoteRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_site_mapping(SiteMapping self, SseSerializer serializer);

  @protected
  void sse_encode_totp_algorithm(TOTPAlgorithm self, SseSerializer serializer);

  @protected
  void sse_encode_totp_config(TOTPConfig self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8_array_16(U8Array16 self, SseSerializer serializer);

  @protected
  void sse_encode_u_8_array_32(U8Array32 self, SseSerializer serializer);

  @protected
  void sse_encode_u_8_array_64(U8Array64 self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vault_metadata_entry(
    VaultMetadataEntry self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pass_tool_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pass_tool_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pass_tool_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pass_tool_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManager =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pass_tool_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pass_tool_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerError =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultManagerErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVaultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pass_tool_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVaultPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVaultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pass_tool_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVault =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultMetadataVaultPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
